### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by waurimal** [vdorie/treatSens#14]
R_interface.cpp:394:8: note: suggested alternative: 'decay'
   std::memcpy(&dst, &src, sizeof(To));
        ^~~~~~
        decay
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/i386/Makeconf:245: R_interface.o] Error 1
ERROR: compilation failed for package 'treatSens'
* removing 'C:/Users/Admin/Documents/R/win-library/4.1/treatSens'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Admin/AppData/Local/Temp/RtmpItN2ZQ/file52587e67288f/treatSens_3.0.tar.gz’ had non-zero exit status

__________________________
why didn't the package(treatSens) install?

**Comment by vdorie** [comment]
Should be fixed in d6f3f8e.
