### ISSUE TITLE
unfixed error

### ISSUE THREAD

**Issue by siynsun** [vdorie/treatSens#5]
Hi Vince, 
I have tested for various combinations. From me, everything works fine except for the weight parameter "trim.wt". There is no error or warning returns when the weight input is invalid. It happens both on continuous and binary treatment. 
I am not sure if it is necessary to fix it.

**Comment by vdorie** [comment]
When we fix this, we should probably only complain if `weights` are set, and otherwise issue a warning when trim.wt is not `missing`.

**Comment by vdorie** [comment]
Updated treatSens and the tests, should be fixed now.
