### ISSUE TITLE
error: could not find function "rmvnorm"

### ISSUE THREAD

**Issue by siynsun** [vdorie/treatSens#6]
Hi Vince,
I also found something a little bit weird, this time when I reinstall the package from the source and tried to run my tests, I got error message called "could not find function "rmvnorm" ". This did not happen before. I then installed the package "mvtnorm", and the function works.But I got NAs for standard error of zeta.y. I have no idea why this happens so I created an issue here in case we need to have a look at some codes inside the package.

**Comment by vdorie** [comment]
Hi Lexie, give me a moment, I have a fix for that I'm about to commit.

**Comment by siynsun** [comment]
No prob!

**Comment by vdorie** [comment]
Fixed in DESCRIPTION and NAMESPACE files.
